### ISSUE TITLE
Warning message regarding Vardict

### ISSUE THREAD

**Issue by SuhanC** [AstraZeneca-NGS/VarDict#132]
Hi, I'm working on several .bam and .bed samples in a single sample mode, 
and it keeps giving me this messages and yields no VCFs.

Use of uninitialized value $exon in substitution (s///) at /media/sysbioinfolab1/hdd1/VarDict-master/vardict line 730.
Use of uninitialized value $exon in uc at /media/sysbioinfolab1/hdd1/VarDict-master/vardict line 731.
readline() on closed filehandle SAM at /media/sysbioinfolab1/hdd1/VarDict-master/vardict line 825.
Use of uninitialized value in split at /media/sysbioinfolab1/hdd1/VarDict-master/vardict line 727.

It's repeating every time i run it..

I ran it with 
     os.system('/media/sysbioinfolab1/hdd1/VarDict-master/vardict -G /media/sysbioinfolab1/hdd1/data/hg19.fa -f 0.01 -N '+sample[s].rstrip('.printrecal')+' -b /home/sysbioinfolab1/NSCLC_DATA/'+sample[s]+  '.bam -c 1 -S 2 -E 3 -g 4 /media/sysbioinfolab1/hdd1/data/NSCLC_bam/'+sample[s]+'.bed | /media/sysbioinfolab1/hdd1/VarDict-master/teststrandbias.R | /media/sysbioinfolab1/hdd1/VarDict-master/             var2vcf_valid.pl -N '+sample[s].rstrip('.printrecal')+' > /media/sysbioinfolab1/hdd1/data/Vardict_vcf/'+sample[s]+'.vardict'+'.vcf')

sample[s] is my filename.

Thank you

**Comment by PolinaBevad** [comment]
Hi Suhan,
Sorry that you have a problem!

Do you have samtools installed in your environment? We use samtools to read fasta and BAM sequences with `faidx` and `view` options and it seems that either samtools is missed, or path to fasta file is wrong. Can you please check this?

**Comment by SuhanC** [comment]
Hi, Thank you for your comment.

I installed samtools in my environment, and i'm using hg19.fa as fasta file for Vardict.
Is there any other possible problems regarding this error message?

thank you.

**Comment by PolinaBevad** [comment]
Suhan, I think you can check if the error appears when you run it not in Python, but directly on command line, to be sure that there are no errors in Python part. For example, I see a space before "var2vcf_valid.pl" and maybe there can be other problems. 

So, just try to run it like this on command line and check all paths, especially that you have access to these files in share folders.
`/media/sysbioinfolab1/hdd1/VarDict-master/vardict -G /media/sysbioinfolab1/hdd1/data/hg19.fa -f 0.01 -N your_sample_name -b /home/sysbioinfolab1/NSCLC_DATA/your_sample_name.bam -c 1 -S 2 -E 3 -g 4 /media/sysbioinfolab1/hdd1/data/NSCLC_bam/your_sample_name.bed`

For test purposes you don't need to add R and var2vcf_valid.pl scripts now, because the error appears in vardict.pl.

**Comment by PolinaBevad** [comment]
Hi @SuhanC,
Do you still have this problem? Can I still help you somehow?

**Comment by SuhanC** [comment]
Hello,
Thanks for your comment.
I tried with VardictJava and i think it's working. 

Thanks again!
