### ISSUE TITLE
Issue running VarDict. 

### ISSUE THREAD

**Issue by shathaa92** [AstraZeneca-NGS/VarDict#135]
Dear VarDict developers , 

I have some issue when running VarDict. whenever I try either the output is empty or bed file not working well. 
I'm calling the variant on simulated bam file. the bed file I used  I got it as 
suggested by ms Polina Bevad Here: https://github.com/AstraZeneca-NGS/VarDictJava/issues/227#issuecomment-495227117

However, all seems fine, but I got this error :
 
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 6
        at com.astrazeneca.vardict.RegionBuilder.buildRegions(RegionBuilder.java:65)
        at com.astrazeneca.vardict.VarDictLauncher.initResources(VarDictLauncher.java:102)
        at com.astrazeneca.vardict.VarDictLauncher.start(VarDictLauncher.java:49)
        at com.astrazeneca.vardict.Main.main(Main.java:15)

Regards

**Comment by PolinaBevad** [comment]
Hi Shatha,
Sorry that you have the issue!

Did you provide the number of columns with chromosome/start/end of the region in the command line? BED files can have different order and count of columns so you have to set it like `-c 1 -S 2 -E 3` based on the numbers of columns in your BED.
You can see the example of command line here: https://github.com/AstraZeneca-NGS/VarDictJava#single-sample-mode

**Comment by shathaa92** [comment]
Dear polina, 
thank you for your quick response, yes I did. I have run it again after posting this issue and the output is empty with no error message  .

Here is my command : 

`module add chpc/BIOMODULES
module load R/2.10.1
module add VarDict/1.70

AF_THR="0.01" # minimum allele frequency

ANC=30

VarDict -G ${refast} -f $AF_THR -N AFR_${ANC}_high.vardict -b ${AFRhi}AFR_${ANC}_sim_high.sorted.bam -c 1 -S 2 -E 3 -g 4 ${VCs}fixed_ref1.bed | teststrandbias.R | var2vcf_valid.pl -N AFR_${ANC}_high.vardict -E -f $AF_THR > ${AFRsimh}vardict/AFR_${ANC}_high.vardict.vcf
`

${refast} is GRCh38 FASTA file. 

Heres a head of the bed file I used: 
chr1	10000	10615	AP006221.1
chr1	10615	177417	AL627309.15
chr1	177417	207666	FO538757.3
chr1	257666	297968	AP006222.1
chr1	347968	501617	AL732372.15
chr1	501617	535988	FO681485.2
chr1	585988	697537	AC114498.2


Regards

**Comment by PolinaBevad** [comment]
Shatha, BED file looks good, one more question: is it tab-delimited? 
If yes, then was the processing of the command ended? If your BAM file is big (for example, WGS or WES run), it can take a big amount of time. Because we have to wait while all variants are processed before filtering them in var2vcf_valid.pl, the VCF file will appear only after the whole VarDict run will be ended.

You can check that output appears with part of the command you used:
`VarDict -G ${refast} -f $AF_THR -N AFR_${ANC}high.vardict -b ${AFRhi}AFR${ANC}sim_high.sorted.bam -c 1 -S 2 -E 3 -g 4 ${VCs}fixed_ref1.bed`
This must give you output almost immediately to the console. If not - we can look at it closer (perhaps part of your BAM file will be helpful). 
If that's working, then try to increase the speed of processing in your full command line by using `-th` option (use number of free cores). It can parallelize VarDict by regions, so it will be much faster.

**Comment by shathaa92** [comment]
I did this 
arDict -G ${refast} -f $AF_THR -N AFR_${ANC}high.vardict -b ${AFRhi}AFR${ANC}sim_high.sorted.bam -c 1 -S 2 -E 3 -g 4 ${VCs}fixed_ref1.bed > samp1.vcf

<img width="2025" alt="Screen Shot 2019-12-03 at 3 46 04 PM" src="https://user-images.githubusercontent.com/38458502/70052387-3b4f4900-15e4-11ea-99f7-53fc8d9c1651.png">

I guess the issues are with R, but I'm not sure.

**Comment by PolinaBevad** [comment]
Just stop VarDict and redirect the file you created like `samp1.vcf | teststrandbias.R | var2vcf_valid.pl -N AFR${ANC}high.vardict -E -f $AF_THR > ${AFRsimh}vardict/AFR${ANC}_high.vardict.vcf`
to check if R works correctly. 
I'm pretty sure that there is no problem, you just have a big BAM file. What is the size of it?

**Comment by shathaa92** [comment]
The BAM file size is 89G,  and I have 100 BAM samples that ranged around the same size. 

I did as you said, there is no output just a header: 

<img width="876" alt="Screen Shot 2019-12-03 at 4 10 25 PM" src="https://user-images.githubusercontent.com/38458502/70053902-8454cc80-15e7-11ea-8b13-d6b2da1a8e68.png">

:(

**Comment by PolinaBevad** [comment]
Can you send me this samp1.vcf output (that you get before R and var2vcf_valid.pl)? I can check if everything is okay with the file. We don't use any specific modules in R, so it must work on clean installed R.

**Comment by shathaa92** [comment]
It is all simulated data so i guess its ok to share :

[samp1.vcf.zip](https://github.com/AstraZeneca-NGS/VarDict/files/3916914/samp1.vcf.zip)

**Comment by PolinaBevad** [comment]
Well, I see that the last line in the file is truncated. Please, try to delete it and then rerun teststrandbias.R and var2vcf_valid.pl steps, it must create output. I got the output VCF about 138 Mb.

For the BAM file sizes that you mentioned and for WGS, you definitely have to set `-th` option otherwise processing can take weeks.
In your case, I would split VarDict step and post-processed steps (R and .pl script) in your script to 2 commands, like:
 
`VarDict -G ${refast} -f $AF_THR -N AFR_${ANC}high.vardict -b ${AFRhi}AFR${ANC}sim_high.sorted.bam -c 1 -S 2 -E 3 -g 4 ${VCs}fixed_ref1.bed > ${AFRsimh}vardict/AFR${ANC}_high.vardict.var`
`cat ${AFRsimh}vardict/AFR${ANC}_high.vardict.var | teststrandbias.R | var2vcf_valid.pl -N AFR${ANC}high.vardict -E -f $AF_THR > ${AFRsimh}vardict/AFR${ANC}_high.vardict.vcf`

Why I recommend doing it is that R functions to process files are working quite slowly and perhaps you will want to process data by parts (by chromosomes, for example). This described here in wiki:
https://github.com/AstraZeneca-NGS/VarDictJava/wiki/How-to-create-gVCF-file-with-VarDict 
https://github.com/AstraZeneca-NGS/VarDictJava/wiki/Best-practics-for-WGS-and-multithreading

I also thinking about moving this R part to VarDict to speed up, and I plan to make the experimental branch this week to run this by option for now.

**Comment by shathaa92** [comment]
Dear polina, 
Thank you for suggesting using  -th, but can you please explain more on how to process by chromosomes? and  how -p option works? 
for example can I call chr1..chr22 

Regards

**Comment by PolinaBevad** [comment]
I think you can try VarDict with -th option first and if processing time in the whole batch with R and pl scripts will be more then day, try to use these scripts:
https://github.com/AstraZeneca-NGS/VarDict/blob/master/additions/split_and_process_var.sh
https://github.com/AstraZeneca-NGS/VarDict/blob/master/additions/run_each_file.sh
The first script split raw result from VarDict by chromosome and create jobs that run second script for each chromosome var file. There are descriptions in the comments in scripts. 
That's why I recommend to split processing into 2 parts (for big BAM files only). The bottleneck is R speed, some functions in it grow quadratically with the file size. So when you will get raw VarDict result (before teststrandbias.R) , you can split the file and process it in smaller parts. 
I looked at realisation of Fisher test in R and off ratio in it differ from typically used, so we should implement it in Java. Perhaps in a while I'll find the specification of R oddratio algorithm and then we can remove this R part.

**Comment by PolinaBevad** [comment]
About pileup option -p: it will output all positions covered by BED file, so it can be used as gVCF. Also no filters will be applied to variants (I.e. by AF, MQ, etc.)

**Comment by shathaa92** [comment]
Dear Polina, 
Thank you for your help. VarDicr is running now. 
Regards
