### ISSUE TITLE
VarDict reports entries where alternate is the same as reference

### ISSUE THREAD

**Issue by MariusGheorghe** [AstraZeneca-NGS/VarDict#137]
Hi,

Running VarDict twice on the same input data, on the same machine, with the same configuration, I observed that the output between the two runs is different. After a `diff` on the output files, entries such as the following represented the differences:

`chr2	25742186	.	A	A	259	PASS	STATUS=StrongSomatic;SAMPLE=samp_1;TYPE=SNV;DP=242;VD=241;AF=0.9959;SHIFT3=0;MSI=1;MSILEN=1;SSF=0;SOR=inf;LSEQ=TCTCTTCGGAGAACGCCTGA;RSEQ=CAGGAATGGTCTGGCCATGG	GT:DP:VD:ALD:RD:AD:AF:BIAS:PMEAN:PSTD:QUAL:QSTD:SBF:ODDRATIO:MQ:SN:HIAF:ADJAF:NM	1/1:242:241:154,87:0,0:0,241:0.9959:0,2:26.1:1:32.8:1:1:0:60:19.083:1:0:0.2	0/0:255:0:0,0:159,96:255,0:0:2,0:26.4:1:34.6:1:1:0:60:27.333:1:0:0.1`

Can you please give some detail why this is happening? Is there some parameter setting that would disable the output of such entries? Thank you in advance.

**Comment by PolinaBevad** [comment]
Hi Marius, 
Sorry that you have the issue!

Can you please check what is the version of VarDict that you use? I remember a similar issue about half a year ago, but we added the fix for this. If it still repeats on last version, could you please share the part of BAM file where it reproduces so I'll check what is happening?

**Comment by MariusGheorghe** [comment]
Hi Polina,

Thank you for your reply. The VarDict version used is 1.5.8. I see that the latest release is tagged with 1.6.
I'll give it a try with the new version and get back to you.

**Comment by MariusGheorghe** [comment]
Hi Polina,

As promised, some feedback on the 1.5.8 and 1.6.0 versions. I've ran both versions on the same data, same machine, with the same parameter configuration. Besides the recurring warning messages:
```
Use of uninitialized value in join or string at ./VarDict-1.6/vardict line 2231.
Use of uninitialized value in join or string at ./VarDict-1.6/vardict line 3250.
Use of uninitialized value in string eq at ./VarDict-1.6/vardict line 4898.
```
I see that indeed using v1.6.0 did not result in calling any variant where the reference and alternate are the same. At least in this run. Why I say in this run, is because between runs (again same data, same machine, same parameters, same VarDict version) I get slightly different sets of variants at each run, which is not awesome from the point of view of result reproducibility.

But coming back to the comparison between versions, I got 2615 variants flagged as PASS using v1.5.8 and 2664 variants flagged as PASS with v1.6.0. From these, 2395 are common, but 220 are unique to v1.5.8 and 269 are unique to the run with v1.6.0.

As I did not find any release notes from VarDict to see what was actually changed between the two versions, and not following every commit message trying to decipher it, can you or your colleague elaborate a bit why such significant differences occurred between the two versions?

Thank you in advance

**Comment by PolinaBevad** [comment]
Hi Marius,

I fixed a lot of places where VarDict produced different results before (it was due to some sorts based on hashes that were using very limited keys), and on our data, we have stable results now. Can you share a part of BAM where you have different results between runs so I can try to run and find out what is happening?

The main version that we support now is VarDictJava, and it has release notes for 1.6.0:
https://github.com/AstraZeneca-NGS/VarDictJava/blob/master/changelog.txt  There were changes for SV analysis, merging of SNVs and calculation of fields for MAPQ, QUAL (so some variants can be filtered now as not PASS). This can lead to different results between versions. Did you compare unique variants by "chr-pos-ref-alt" combination or by comparing full string? Some of the variants fields will definitely differ between versions after these fixes.

**Comment by MariusGheorghe** [comment]
Hi Polina,

Thank you for all the details and thank you for the link to the change log. I do see there are quite some fixes in the newer version. Is v1.7.0 stable also? 

I did not perform two runs of v1.6.0 on the same data, only with v1.5.8 and there I did get different results between runs. I will take your word that v1.6.0 provides robust sets of variants between runs. 

Unfortunately, I cannot provide you with our BAM files due to data sensitivity. We will most probably upgrade the version of VarDict in our pipeline and then we will perform reproducibility tests. If necessary, I will get back to you.

Again, thank you for your support and keep up the good work :]

Marius

**Comment by PolinaBevad** [comment]
Marius, thank you! 
Yes, VarDictJava 1.7.0. stable, we use it in our pipelines on bcbio and it is released in conda also. But I see that for some reason 1.7.0 wasn't released in Perl (I guess we just forget). We run all integration tests for Perl version when making changes, but don't use it in production a lot at the moment. All 1.7.0. changes are in master branch, so you can just clone it if needed. Anyway I really recommend to update your version to VarDictJava 1.7.0, it has multithreading (by `-th` option), it is much faster, we have a lot of tests there and better support of errors and warnings. 
I think the variants between 1.5.8. and 1.6.0. mostly were changed because of SNV merging, because we fixed the collapsing of variants in one (as MNV) and because of work on reproducibility (there were changes in realignment, so some variants can have different ALT).

**Comment by MariusGheorghe** [comment]
Okay. Thank you! As soon as I get to it, then I'll update to VarDictJava 1.7.0. That will help a lot having it faster and with more explicit error messages. I did see that in 1.6.0 for some reason the `-th` option was gone, but didn't ask myself to many questions as of why. :]

Glad to hear you've put in place integration tests and aiming for result reproducibility. 
Again, thanks Polina for all the support. Should I close the issue or?

**Comment by PolinaBevad** [comment]
I think yes, you can close it. 
If you will have any problems with VarDictJava, just create another issue in this repository: https://github.com/AstraZeneca-NGS/VarDictJava
`-th` option doesn't work for perl version, because multithreading isn't implemented here, so vardict will just warn about the unrecognized option. In VarDIctJava if you set `-th number_of_threads`, then it will run each BED region on a separate thread, so it will work almost linearly faster by the number of threads.

Thank you!

**Comment by MariusGheorghe** [comment]
Okay. That's cool. As long as the "super-dynamic-ever-increasing-never-releasing" java heap size behaves I guess :D In any case we're cautious to limit each process' resources, especially the ones based on java. 
Will do stick to the other repo if I find other issues. 
Thanks Polina!
