### ISSUE TITLE
Maftools to visualize verdict results

### ISSUE THREAD

**Issue by biobug16** [AstraZeneca-NGS/VarDict#140]
Hi @PolinaBevad and @vladsaveliev  
I want to visualize VarDict vcf or maf files. For which I am planning to use maftools but the file format from VarDict does not seem to be compatible with maftools. 

Any suggestion towards this will be highly appreciated.
Thanks

**Comment by PolinaBevad** [comment]
Hi @biobug16,

Did you try vcf2maf tool (https://github.com/mskcc/vcf2maf)? It is used to convert VCF format to one that maftools can analyze.  I know this can be a little bit complicated because you have to install ensembl VEP locally also (https://gist.github.com/ckandoth/5390e3ae4ecf182fa92f6318cfa9fa97), but I don't know about other tools to convert VCF in MAF-compatible format that are maintained at the moment.

**Comment by biobug16** [comment]
Hi @PolinaBevad 
I tried vcf2maf and it helped.
Thanks!
