### ISSUE TITLE
bam format

### ISSUE THREAD

**Issue by jp3117** [AstraZeneca-NGS/VarDict#20]
Hello,

I am pretty interested in this software. I installed the code and successfully ran your sample code. However when I switched to my sample bam file, the error messages were raised:

Use of uninitialized value in join or string at vardict.pl line 2365.
Use of uninitialized value in join or string at vardict.pl line 2367.

The process failed. I used the samtools to check the difference between your sample bam file and my sample bam file. I found my bam file contains more fields than yours. please see the below from my sample bam file:

HWI-ST1377:449:HVKW2ADXX:2:2203:3926:4692       81      17      7580123 60      101M    =       7579813 -411    CACTCCTGCCCCACCCCTCACCAGCCATGCACTTCTTTGAGGAAAAGACAATCAGAGAGGGACTTCCAACCTTCCCACCACTAAATCCCCAAGACTTCCTA   C?@AEGDGGGGCAGGGFCFAGGGEGGCDFHCGEDFDDEEDCECCCEECEBCBFDDDEDBBEBECBCEBBCDCBCBFACEAEBBBBACDCGBEFBGDBCA>A  MC:Z:101M       BD:Z:KPMMPSRQKKPKNJJMMMKNOPOPOOOPPJOLKLLCLMKLLKDDJKOJKLNLOKKKKLILOOLKLNKKMLLKLINJMNJONKDLNLIINKKLPPNMOMOLL      MD:Z:101        PG:Z:MarkDuplicates     RG:Z:sample1        BI:Z:PTQQTTUSNNSQRMMQQSPRRSTRRSRTTPSPOOPHPRMPOPHHNOPNROPRROMOMPLOPSPOPQRPQPPOPKPNPQNSQPGNOOKKPRNOPSQPRQSPP     NM:i:0  MQ:i:60 OQ:Z:DC@?DDBDDDD@;DDDBCA=DDECFDFDFFEFHEHJJHHIIIJJIJIIJJGGIIGGIJJJIGGJIJIHGJIHGJIHFJIHJIIIIGJJHHHHHFFFFFCBB      AS:i:101        XS:i:20

does this bam format cause the program fail?

Thanks.
Marissa

**Comment by mjafin** [comment]
Hi Marissa,
Thanks for your interest in using VarDict. I wonder what your bed file looks like? Apologies, sometimes the error messages and warnings are not very informative. 

If you're interested in running a faster version of VarDict in a fully blown pipeline environment, we have integrated Java-VarDict in bcbio, see https://github.com/chapmanb/bcbio-nextgen

**Comment by wangdongli** [comment]
hello， @jp3117 ，I am a beginner in bioinformatics and would like to ask you some simple questions.

AF_THR="0.01" # minimum allele frequency
vardict -G /path/to/hg19.fa -f $AF_THR -N sample_name -b /path/to/my.bam -c 1 -S 2 -E 3 -g 4 /path/to/my.bed | teststrandbias.R | var2vcf_valid.pl -N sample_name -E -f $AF_THR

In the above command, the parameter -N sample_name reprensents what？
thanks.

**Comment by mjafin** [comment]
Hi @wangdongli, `-N` specifies the sample name that will be used in the vcf file. Let us know if you have any other questions.

**Comment by wangdongli** [comment]
Thank you! I‘m so excited to receive your reply. OK,then probloms as follows：

1.parameter -N  is must? That means I have bed file and bam file,can I do the SV detection?

2.the command can be ran in Windows dos?

thanks!

**Comment by wpowers1** [comment]
Hello, 

I am having the same issue as Marissa, I am able to use the program with your sample files as well as with publicly available BAM files. Using a BAM file that has additional columns causes the program to fail. Has this been identified as an issue, and are there any work arounds besides removing these fields from the BAM file?

Thanks,
Winslow

**Comment by mjafin** [comment]
Hi Winslow,
Thanks for your interest in VarDict and apologies for any bugs in the code. The number of BAM columns might be a red herring. I would suggest the following:
- Please try running the VarDictJava code rather than VarDict Perl
- If you're not super familiar with VarDict, may I suggest you run it via bcbio-nextgen? https://github.com/chapmanb/bcbio-nextgen 
- If all else fails, please provide a BAM snippet, the corresponding BED file snippet and the command you use to run VarDict

**Comment by PolinaBevad** [comment]
Hi Marissa,
This issue is outdated so I will close it. The initial problem was presumedly due to absent checking for the presence of position in reference to get sequences for mismatches. Also, perhaps it is better to use VarDictJava version because it has more checks for such cases.  
In any case, if some problems still appear, then you can create the issue with BAM part where it occurs.  It will be very helpful.
Thank you!
