### ISSUE TITLE
error in fisher.text

### ISSUE THREAD

**Issue by ltfang-bina** [AstraZeneca-NGS/VarDict#5]
I've received two errors on a pair of tumor-normal data set (hg19 reference). The ".var" file was generated with the following command:

vardict -G hg19.fa -f 0.01 -h -b 'tumor.bam|normal.bam' -z -F -c 1 -S 2 -E 3 -g 4 region.23.bed > region.23.var

The error occurred here: cat region.24.var | awk 'NR!=1' | testsomatic.R > region.24.testsomatic

Error in fisher.test(matrix(c(d[i, 10], d[i, 11], d[i, 12], d[i, 13]),  : 
  all entries of 'x' must be nonnegative and finite
Execution halted

Have you guys run into these before?

Thanks.

**Comment by etolpygo** [comment]
I am seeing the same issue. 
Run on mixed NA12878/NA12882 samples.

This happens when some of the values in matrix(c(d[i, 10], d[i, 11], d[i, 12], d[i, 13]) are converted to NA

offending line from the intermediary var file (as produced by vardict):
CGP-221   USP6;USP6;USP6_5'UTRexon_intron_ENST00000574788 chr17   5032410 5032410 G       A       167     167     0       0       85      82      A/A     1.0000  0;2     27.4    1       38.3    1       60.0    82.500  1.0000  0       0            2.000   1       1.1     165     165     GTAGAGTGGGTGCTGTTCCC    AATGTACCCATTCGACAGGT    chr17:5030835-5034101   SNV

**Comment by etolpygo** [comment]
this is weird, but it appears that, at least in this case, an odd number of **`'`** symbols in the file is throwing it off.

**Comment by nkarulin** [comment]
Hello, @etolpygo!
While I have successfully reproduce @ltfang-bina 's case, there is no error during teststrandbias.R step on the 3 lines example which you have provided (although there is an odd number of `'` symbols).
Could you please provide test data, which cause the error, so we could reproduce it?

**Comment by manasa-surakala** [comment]
Hi, 

I am running verdict for RNAseq samples and got this error - 
Error in fisher.test(matrix(c(d[i, 10], d[i, 11], d[i, 12], d[i, 13]),  :

**Comment by chapmanb** [comment]
Manasa -- this is a bug in 1.5.4 that we have a test case and possible fix for: https://github.com/AstraZeneca-NGS/VarDictJava/pull/129 We'd need to get this pulled in, test and create a new vardict-java release. I know @pcingola is on this but not sure about the time frame. A quick fix is to us 1.5.1 for your project to avoid the issue.

**Comment by PolinaBevad** [comment]
@ltfang-bina, @manasa-surakala, hello!
In the last releases, we no longer received similar errors. We added checks for negative values with adjustment of them to zero in Java version, so if possible, please, use VarDictJava instead of perl version. 
I will close this issue, and please re-open it or create another issue if you have any questions.
Thank you!
