### ISSUE TITLE
sorting and indexing bam files

### ISSUE THREAD

**Issue by gpuwarrior** [AstraZeneca-NGS/VarDict#69]
Hi. This is the first time I am using vardict.
I was wondering if the bam files need to be sorted and indexed before using vardict?
And what does "corr" stands for in this bam file? Thanks!
sample1_sorted.corr.bam

**Comment by PolinaBevad** [comment]
@gpuwarrior, hello!
Apologies for the late reply!
Yes, VarDict needs indexed BAM (and because the index is created from sorted BAM, it must be also sorted). 
I can not tell what "corr" means in the BAM file, but I guess it is the version of the BAM file after applying some filters or recalculations. 
I will close the issue but you can reopen it if needed.
Thank you!
