### ISSUE TITLE
Proper format for bed file in amplicon mode

### ISSUE THREAD

**Issue by dh10** [AstraZeneca-NGS/VarDict#7]
My understanding is that the region start and end positions are for the Amplicon, inclusive of primer regions. And the segment start and end correspond to the targeted region excluding the primer region. Is this correct?  I have not seen it documented.

**Comment by zhongwulai** [comment]
For amplicon awareness variant calling, a BED file with 8 columns are required.  Below is an example:
chr1    46713345        46713502        RAD54L  0       .       46713363        46713481
chr1    46713418        46713578        RAD54L  0       .       46713435        46713561
chr1    46713483        46713641        RAD54L  0       .       46713504        46713621

It's 0-based, as specified by BED.  There first two numbers include primers, and the last two numbers are insert only.  The 5th and 6th columns are not used by VarDict.  VarDict will perform in silico trimming of primers, and for variants in overlapping amplicons, they needs to be detectable by both  amplicons, otherwise, they're flagged as amplicon-bias, and likely false positives.  By default, a read pair is assigned to the amplicon if 95% of read pair (including primers) overlaps with the amplicon (the first 2 numbers in BED file) and both ends are within 10bp of the amplicon edge.  You can change them through "-a 10:0.95".

Please note: VarDict currently can't do paired analysis in amplicon mode.

Thanks!

**Comment by PolinaBevad** [comment]
Duane, hello!
The issue will be closed because the requirements for amplicon mode were already documented in Java version of Vardict.
Thank you!
