### ISSUE TITLE
GATK4 Base Quality Score Recalibration (BQSR)- Should I be using this with VarDict?

### ISSUE THREAD

**Issue by AlisonKennedy** [AstraZeneca-NGS/VarDict#71]
Hi,

I was wondering if I could get your comments on whether its appropriate to use VarDict on data that has been put through Base Recalibration using GATK4?

Many thanks

**Comment by PolinaBevad** [comment]
Hello, Alison,
Sorry for the very late reply!

Quality scores can be adjusted after using Base Recalibration and these changes can be very significant.
This can cause a problem like this: https://github.com/AstraZeneca-NGS/VarDict/issues/61 where no variant was found on the region after adjustment and option `-q 15` was needed for variants to appear. 
So if you use Base Recalibration, you can check what was changed and adjust parameters for VarDict if needed. Option `-p` can be helpful in such a case when you run some tests on the region (in the whole run it can be very slow) because it can output variants before filtering and you will see what filters you have to adjust.
I will close this issue, but I will add this to wiki of VarDictJava version. 
Thank you!
