### ISSUE TITLE
VarDict not calling SNPs close to edgess of bed region when using an amplicon-based ngs assay

### ISSUE THREAD

**Issue by rebeccaforrester** [AstraZeneca-NGS/VarDict#84]
Hi,

I wondered if you have come across any problems with using VarDict to call variants at the very edges of targeted regions (within +1 and +4 of edge) using an amplicon-based NGS assay. 

I have been doing a validation and had a couple of false negative results. One variant was at +1 from the 3' end of the targeted bed region and another at +4, both failed to be called.

To test further, I spiked in the variants at a frequency of 100% and despite being very clear in IGV, they are still not detected. Interestingly for comparison, I also did the same to a BAM file from a hybridisation assay using the same variants/positions and VarDict called these variants fine.

Any info you have would be greatly appreciated, 
Many thanks.

**Comment by PolinaBevad** [comment]
@rebeccaforrester, hello!
Could you please provide the part of BAM file where these false negative results appear so we can debug the error? BED file with amplicon region and the command line that you launched will be good too. 
Thank you.

**Comment by rebeccaforrester** [comment]
Do you have an e-mail address I could send these to? I am struggling to upload.

Thanks

**Comment by PolinaBevad** [comment]
@rebeccaforrester, of course, you can send the data to email polina_bevad@epam.com.

**Comment by PolinaBevad** [comment]
@rebeccaforrester, hello!
We tested this case and everything seems to be ok: by default, Vardict will filter variants that are within 5 positions from the edge because they are considered as false positive, but you can change this with option '-P ' and determine how many positions you want to set. For example, if you set '-P 1' both missing variants will be in the output. 

You can look to this part of vardict.pl to know about other options and their default values:
https://github.com/AstraZeneca-NGS/VarDict/blob/master/vardict.pl#L4740 
Also we have a documentation for VarDictJava version that supports multithreading and is faster then perl version (https://github.com/AstraZeneca-NGS/VarDictJava/), but it support few options that perl version doesn't support and vice versa.

**Comment by rebeccaforrester** [comment]
@PolinaBevad That's great I will add in the -P flag, thanks very much for your help with this!

**Comment by PolinaBevad** [comment]
@rebeccaforrester, great that it helped! I will close the issue.
